### ISSUE TITLE
Update for Godot 3

### ISSUE THREAD

**Issue by Benoit9** [jrimclean/rawpacker#2]
Hi @empyreanx , I got rawpacker to compile and mostly run in Godot 3.1.1. Should I finish and make a PR? Just checking this repository is still active before I put more work into it. Thanks!

**Comment by empyreanx** [comment]
Hi @Benoit9,

This repository is largely abandoned. If you like, you could start your own 'rawpacker3' (or some such) repository and I'll include a link to it in the README.

**Comment by Benoit9** [comment]
@empyreanx Thank you for the answer for the offer. But I am not planning on maintaining it either, that's why I was checking first.

**Comment by organicpencil** [comment]
This fork is somewhat maintained https://github.com/organicpencil/rawpacker3
